### ISSUE TITLE
Annoying system beep when booting

### ISSUE THREAD

**Issue by geckolinux** [SpiralLinux/SpiralLinux-project#109]
### Discussed in https://github.com/orgs/SpiralLinux/discussions/100

<div type='discussions-op-text'>

<sup>Originally posted by **quadransmuralis** August 20, 2022</sup>
Hello,
When booting Spiral Linux with the Gnome desktop from a live usb there is an annoying beep.
Is there a way to stop this deafening behaviour?
Thx </div>

**Comment by northivanastan** [comment]
The same thing occurs with official Debian images. I believe it has something to do with the GRUB_INIT_TUNE option in grub's configuration file (/etc/default/grub on my system).

**Comment by geckolinux** [comment]
@northivanastan Right, in the `staging` images I have on Sourceforge I think the beep should be disabled now on the live ISO.

**Comment by geckolinux** [comment]
Removed in the SpiralLinux 11.220925 release.
