### ISSUE TITLE
SpiralLinux with UKUI ?

### ISSUE THREAD

**Issue by Neocamelus** [SpiralLinux/SpiralLinux-project#117]
Hello SpiralLinux , 

Do you plan to release a version with the UKUI Desktop Environment ?

Regards

**Comment by geckolinux** [comment]
Hi there! Interesting, I didn't know that Ukui was available in the Debian repos... Have you ever used it in Debian Stable?

**Comment by Neocamelus** [comment]
When an amateur like me does that, you get an incomplete and unusable environment. I found myself without a dock and without an application menu :sweat_smile: 

But people more experienced than me got a usable system: [Debian com ambiente desktop UKUI](https://www.youtube.com/watch?v=QK6xT6pU_9U)

**Comment by geckolinux** [comment]
> When an amateur like me does that, you get an incomplete and unusable environment. I found myself without a dock and without an application menu 

;-) Yep, in my initial tests I'm not doing much better myself. But thanks for that Youtube video, it's obviously possible to make it work, but as always it will require figuring out the ideal combination of packages. I'll keep experimenting and report back here with the results. Thanks again for the heads-up!

**Comment by geckolinux** [comment]
Well, it looks pretty good actually:

![Screenshot from 2022-09-09 12-41-04](https://user-images.githubusercontent.com/2692138/189430843-d9449d9a-6c91-4ac2-8777-ea1bc9613d8d.png)

It was installed with the following packages on top of SpiralLinux Builder:
`libqt5-ukui-style1 lightdm qt5-styles-ukui qt5-ukui-platformtheme ukui-control-center ukui-greeter ukui-media ukui-media-common ukui-menu ukui-panel ukui-polkit ukui-power-manager ukui-power-manager-common ukui-screensaver ukui-session-manager ukui-settings-daemon ukui-settings-daemon-common ukui-sidebar ukui-themes ukui-window-switch ukwm peony peony-extensions qt5-gtk-platformtheme`

However, there's a fairly major limitation in that the applications menu doesn't find Flatpaks that have been installed.

**Comment by Neocamelus** [comment]
Voila, I know how to occupy my weekend.
Thank you, Geckolinux :hugs:

**Comment by geckolinux** [comment]
I guess I'll close this issue for now. An official UKUI spin of SpiralLinux doesn't really seem feasible if Flatpaks don't appear in the menu. But for those who don't care about that functionality it's pretty easy to just install UKUI with a Builder base system or even on top of one of the other desktop environments. If you do manage to find a way to make Flatpaks automatically appear in the UKUI menu please let me know.
