### ISSUE TITLE
I think it better to allow setting btrfs subvol when installing

### ISSUE THREAD

**Issue by CicadaSeventeen** [SpiralLinux/SpiralLinux-project#139]
Spiral Linux uses btrfs as default, while it does not allow user to choose settings about btrfs subvol. Although the default subvol setting of SpiralLinux is OK (much better than debian default), it is sad that I cannot set it myself as I want. For example, I may want to make `/opt` and '/usr/local' or `/var` to be subvol. While former two is easy to do so after installation, making `/var` a subvol after installing is quite annoying.
In my opinion, openSUSE and Fedora do well at this aspect. I know openSUSE's powerful installer is from YAST which is quite hard to be transplanted to other distros. But Fedora (or I should better say, Redhat) 's `Anaconda` is a great installer too. Maybe it can gives you some inspiration.
Thanks.

**Comment by geckolinux** [comment]
Hi there, thanks for the comment. This isn't something that I can implement until the Calamares installer implements it. Feel free to add your thoughts to the feature request here:
https://github.com/calamares/calamares/issues/1580
