### ISSUE TITLE
Asian language support problem

### ISSUE THREAD

**Issue by CicadaSeventeen** [SpiralLinux/SpiralLinux-project#140]
Some Asian languages (like Chinese, Japanese, Korean and so on) need input method so that it can be input correctly. But now in SpiralLinux there is no input method pre-installed even if I choose there languages as default. However, since Debian has good language support it is easy for old users to install input method they want.

But since SpiralLinux is for user-friendly I think we should talk about this problem. The problem is, distros like ubuntu or openSUSE pre-install input method once user choose these languages as default when installing, but it can also make things worth.

For example,  to input Chinese, we have two major input method: `ibus` and `fcitx5`. `ibus` works very well on `Gnome` but `fcitx5` works better on other desktop especially under `wayland`. We also have some out-of-date input method like `fcitx` and `scim`. Ubuntu chooses to pre-install `fcitx` for Chinese language and openSUSE pre-intsalls both `ibus` and `fcitx`. Although it provides out-of-box input experience but users will have to struggle if they want a better input method. 

(BTW, Japanese sometimes prefer to use `uim`)

I think we had better think of such situation. I am thinking about making a script or program to guide users to choose input method. I would like to know your opinion here.

Besides, I find some options not translated maybe because you change them from vanilla Debian. I think I can actually help to provide some translation but there is not a promise, because I suffer from depression there years so that I may even have several months that cannot concentrate for any work.

**Comment by geckolinux** [comment]
Thanks for the suggestion.

If only `fcitx` or `ibus` is preinstalled the user would still have to install the specific language character set they need (Traditional Chinese, Simplified Chinese, Japanese, etc.) right? I understand the vanilla Debian and openSUSE provide this out-of-the-box, but with Calamares this is much more difficult, and plus it would require downloading packages during installation, which I try to avoid.

I'm thinking this would best be handled as a documentation improvement in the SpiralLinux wiki.

**Comment by CicadaSeventeen** [comment]
I do not know anything about Calamares. Sounds like it is just a tool to release system from tar?
In theory we can provide a program to guide user to choose input method, or at least a bash script. Debian has a program to choose input method actually, but it can just used to choose input methods that have been installed on system.
However, before that we can truly write a wiki. You can put wiki on default desktop just like opensuse's hello page. I can help you to write about input method installation in about one week, but only about Chinese and Japanese. For Vietnamese and Korean or other languages, neither can I speak it nor I can find someone using Linux speaking such languages.

**Comment by CicadaSeventeen** [comment]
> Thanks for the suggestion.
> 
> If only `fcitx` or `ibus` is preinstalled the user would still have to install the specific language character set they need (Traditional Chinese, Simplified Chinese, Japanese, etc.) right? I understand the vanilla Debian and openSUSE provide this out-of-the-box, but with Calamares this is much more difficult, and plus it would require downloading packages during installation, which I try to avoid.
> 
> I'm thinking this would best be handled as a documentation improvement in the SpiralLinux wiki.

https://github.com/CicadaSeventeen/debian-input-method-guide
This is the script. I do not do any grammar & spelling check and do not add links. Need you to check and edit it and put it in WIki. If any reports find mistakes, feel free to ask me and I will find out what is wrong.

**Comment by geckolinux** [comment]
Excellent, thank you very much. I added your guide to the documentation:
https://github.com/SpiralLinux/SpiralLinux-project/wiki#how-to-install-non-english-input-methods
