### ISSUE TITLE
Switch from Synaptics to libinput

### ISSUE THREAD

**Issue by CicadaSeventeen** [SpiralLinux/SpiralLinux-project#142]
I try xfce on my two laptop and find that reverse scroll direction does not work. While reverse scroll direction of mouse or like Thinkpad red Trackpoint works.
Similar problem exist in Xubuntu 22.04 and your GeckoLinux, but not at debian 11.5 xfce. Maybe it is because of you forget a package.

**Comment by CicadaSeventeen** [comment]
I find it is a known gtk3 bug.
[https://bugs.launchpad.net/ubuntu/+source/xfce4-settings/+bug/1368402](https://bugs.launchpad.net/ubuntu/+source/xfce4-settings/+bug/1368402)
Then it is time to find out how debian workaround it.

**Comment by CicadaSeventeen** [comment]
Bingo. Removing `xserver-xorg-input-synaptics` and then this bug will disappear.

In fact now `lubinput` is so strong that it can drive most input device. Debian actually only pre-install three packages: `xserver-xorg-input-libinput` `xserver-xorg-input-input-all` and `xserver-xorg-input-wacom`.  If more `xserver-xorg-input-xxx` is installed, it can be preferred to use and they may not be as good as `xserver-xorg-input-libinput` so that it may bring some bugs. ( Another 'classical' bug is that mouse freeze after resuming from suspend )

Most device may run on `xserver-xorg-input-libinput` best. However, I am not saying that there are not any input devices that cannot be driven by `libinput` but by other drivers. I do not know whether removing other drivers or at least moving `xserver-xorg-input-synaptics` is a good idea. That is, to gain better out-of-box experience for most devices but can potentially harm some little mount of strange devices. But you can think about it.

**Comment by CicadaSeventeen** [comment]
Fedora, Linux Mint, LMDE, Ubuntu, debian(xfce)... all use `libinput` only. Manjaro and openSUSE use more, but still not using `mouse` `mulitouch` `synaptics ` or other drivers for mouse or touchpad. Xubuntu have similar bug as SpiralLinux because it do preinstall other packages here.
Besides, debian metapackage `xserver-xorg-input-all` only contains packages below:
![image](https://user-images.githubusercontent.com/86961676/194741136-597da30e-372a-45e0-b16a-41784151de40.png)
So I suggest to drop other packages since most distros do so, especially debian-series distros.

**Comment by CicadaSeventeen** [comment]
@geckolinux

**Comment by geckolinux** [comment]
Sorry @CicadaSeventeen for the slow reply.

Very nice find! During the initial development I tested with and without `xserver-xorg-input-synaptics` on my Thinkpad T440s, and things like disabling the touchpad while typing and 2-finger scrolling didn't work with `xserver-xorg-input-libinput`. But after testing today it looks like your theory is correct:
> If more `xserver-xorg-input-xxx` is installed, maybe system will prefer to use them and then cause bugs.
Specifically, it looks like the problematic packages are:
- `xserver-xorg-input-mouse`
- `xserver-xorg-input-multitouch`
- `xserver-xorg-input-mutouch`

It should be noted that there will be different GUI control options in Plasma and XFCE for touchpads under `libinput`:

### Synaptics
![Screenshot_2022-10-16_21-36-03](https://user-images.githubusercontent.com/2692138/196060033-f0c81f1a-e87c-44f4-8b7b-d4d47e88d3d7.png)

-----------

### `libinput`
![Screenshot_2022-10-16_21-44-20](https://user-images.githubusercontent.com/2692138/196060034-83b599b4-b6ee-4c89-a020-f928118abb1d.png)

-----------

### Synaptics
![Screenshot_20221016_211200](https://user-images.githubusercontent.com/2692138/196060036-c02d91b5-b835-4ea5-851e-e690c4b10929.png)

--------------

### `libinput`
![Screenshot_20221016_205654](https://user-images.githubusercontent.com/2692138/196060035-7fe26fa4-911b-4645-b126-0cd65ab0b965.png)

------------

But despite the lack of configuration, it looks like `libinput` has decent default settings, although less configurable in some desktop environements. And as you say, it looks like the best for handling most hardware by default.

This will be changed in the next release.

**Comment by CicadaSeventeen** [comment]
On my thinpad p15v, the package that make problem is `xorg-xserver-input-synaptics`

**Comment by geckolinux** [comment]
>> Specifically, it looks like the problematic packages are:
>> - `xserver-xorg-input-mouse`
>> - `xserver-xorg-input-multitouch`
>> - `xserver-xorg-input-mutouch`

> On my thinpad p15v, the package that make problem is `xorg-xserver-input-synaptics`

Yes, I meant that those three packages are what prevents it from working properly with `libinput` when `xorg-xserver-input-synaptics` is removed.

**Comment by geckolinux** [comment]
Implemented in https://github.com/SpiralLinux/SpiralLinux-project/releases/tag/12.231001
