### ISSUE TITLE
Unable to Boot

### ISSUE THREAD

**Issue by LuisArtDavila** [SpiralLinux/SpiralLinux-project#158]
Hi, I'm unable to boot using the latest ISO. I'm using Ventoy. Whenever I try to boot into any of the options (5.10, 5.18 and their respective failsafe options) I just end up with a black screen without any error messages. I haven't tried Spiral Linux before but Gecko Linux seems to boot just fine so I'm not sure what the problem is.

Edit: I forgot to mention I'm using a 6700 XT GPU and the GNOME image, and I verified that the image wasn't corrupted by comparing the checksum of the downloaded file to what's on SourceForge. I also can't seem to get the GNOME image to work even in VirtualBox but the XFCE one works just fine. Could the GNOME image be broken maybe?

**Comment by CicadaSeventeen** [comment]
If I do not misunderstand you:
You cannot boot gnome image on your 6800XT.
You cannot boot gnome image in Vbox.
You can boot Xfce image in Vbox.

If I understand correctly?

Besides, can you boot Xfce image on your 6800XT?

**Comment by geckolinux** [comment]
> but the XFCE one works just fine.

Hi, could you please confirm if the XFCE image boots for you with real hardware?
The Gnome image has been tested to work in VirtualBox and with real hardware.

If you still can't make it boot on your real hardware could you please try the previous release?
https://sourceforge.net/projects/spirallinux/files/11.220628/
I wonder if [this issue](https://github.com/SpiralLinux/SpiralLinux-project/issues/141) is possibly preventing the current release from booting because of some proprietary Nvidia packages being pre-installed due to a Debian bug.

**Comment by CicadaSeventeen** [comment]
> Hi, I'm unable to boot using the latest ISO. I'm using Ventoy. Whenever I try to boot into any of the options (5.10, 5.18 and their respective failsafe options) I just end up with a black screen without any error messages. I haven't tried Spiral Linux before but Gecko Linux seems to boot just fine so I'm not sure what the problem is.
> 
> Edit: I forgot to mention I'm using a 6700 XT GPU and the GNOME image, and I verified that the image wasn't corrupted by comparing the checksum of the downloaded file to what's on SourceForge. I also can't seem to get the GNOME image to work even in VirtualBox but the XFCE one works just fine. Could the GNOME image be broken maybe?

https://github.com/SpiralLinux/SpiralLinux-project/discussions/161

Here gnome version does seem wired but at least I do not have such problem.

**Comment by geckolinux** [comment]
> #161
> Here gnome version does seem wired but at least I do not have such problem.

Gnome is always different from others because it's the only one that uses the GDM login manager and it has deeper integration with systemd.

**Comment by skybreakerrd** [comment]
Similar issue happens with me as well with latest gnome iso(11.220925), unable to boot into live setup with any of the kernels, it's stuck on blank screen with cursor. Any logs I can provide which can help, Thanks

**Comment by geckolinux** [comment]
@skybreakerrd Sorry for the trouble. What sort of hardware do you have? Could you test a different ISO with one of the other desktop environments?

**Comment by skybreakerrd** [comment]
First of all thanks for Spiral Linux, it really makes snapper and btrfs easily accessible with debian.
I have tried with latest kde iso, and not able to boot into live desktop with it either, tested with both secure boot on and off.And when selected fail-safe mode to check the message, it's stuck on the part of the message mentioned below., I am having an encrypted nvme drive which is currently running ubuntu if that helps. Happy to help.

**Fail Safe mode log:**
nvme0: Identifying controller failed.
nvme0:  Removing after probe failure status: -5

**Hardware Details:**
AMD Ryzen 7 7700X 8-Core Processor
00:00.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Device 14d8
00:00.2 IOMMU: Advanced Micro Devices, Inc. [AMD] Device 14d9
00:14.0 SMBus: Advanced Micro Devices, Inc. [AMD] FCH SMBus Controller (rev 71)
00:14.3 ISA bridge: Advanced Micro Devices, Inc. [AMD] FCH LPC Bridge (rev 51)
01:00.0 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 XL Upstream Port of PCI Express Switch (rev c0)
02:00.0 PCI bridge: Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 XL Downstream Port of PCI Express Switch
03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M] (rev c0)
03:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21/23 HDMI/DP Audio Controller
04:00.0 Non-Volatile memory controller: Kingston Technology Company, Inc. Device 5013 (rev 01)
0c:00.0 SATA controller: ASMedia Technology Inc. ASM1062 Serial ATA Controller (rev 02)
0e:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8125 2.5GbE Controller (rev 05)
0f:00.0 USB controller: Advanced Micro Devices, Inc. [AMD] Device 43f7 (rev 01)
10:00.0 SATA controller: Advanced Micro Devices, Inc. [AMD] Device 43f6 (rev 01)
11:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Raphael (rev c3)
11:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt Radeon High Definition Audio Controller
11:00.2 Encryption controller: Advanced Micro Devices, Inc. [AMD] VanGogh PSP/CCP
11:00.3 USB controller: Advanced Micro Devices, Inc. [AMD] Device 15b6
11:00.4 USB controller: Advanced Micro Devices, Inc. [AMD] Device 15b7
11:00.6 Audio device: Advanced Micro Devices, Inc. [AMD] Family 17h/19h HD Audio Controller
12:00.0 USB controller: Advanced Micro Devices, Inc. [AMD] Device 15b8

**Comment by skybreakerrd** [comment]
@geckolinux  Anyway I can help here to find the problem, I have installed spiral in my laptop where it works perfectly fine, liveusb not booting with my pc though, think it's something to do with hardware maybe.?
