### ISSUE TITLE
Proposal for improvements to desktop logos (logo-LXQt, logo-Mate.png) 

### ISSUE THREAD

**Issue by JnBenites** [SpiralLinux/SpiralLinux-project#159]
![logo-LXQt](https://user-images.githubusercontent.com/55644440/195795677-6ef70ce6-672f-4bf9-85c0-24fdd9671e51.png)
![logo-Mate](https://user-images.githubusercontent.com/55644440/195795682-e2bc45ed-629b-45c3-8cd1-e07f228c57eb.png)

**Comment by geckolinux** [comment]
Many thanks! Great job. I just updated them on the website.
