### ISSUE TITLE
Vanilla Debian theming

### ISSUE THREAD

**Issue by deff245** [SpiralLinux/SpiralLinux-project#160]
Hello, first I wanna say I'm completely in love with Spiral, I converted all my machines, both at home and work. Yesterday one of my colleagues was intrigued by Spiral when he saw me running it and asked to try it for a bit. He was impressed by performance and said he would gladly use it as a daily driver if there was an option to choose vanilla Debian theming. 
Is it possible to add such an option? On EndeavourOS it's possible to choose between EOS and vanilla Xfce theming with a one click, it would be nice addition to see something similar on SpiralLinux for users that prefer default Debian style. Cheers and keep doing a great job.

**Comment by CicadaSeventeen** [comment]
You can just edit theme yourself. Xfce is very easy to customize.

**Comment by geckolinux** [comment]
Hi there @deff245 , really glad to hear that it's working well for you!

Regarding reverting to the vanilla Debian theming, yep, it's pretty easy. Just delete `.config/xfce4` and `.config/dconf` from the home directory of the users. To prevent future new user accounts from picking up the SpiralLinux default theme you can also delete those same two directories from `/etc/skel/` as well.

Just be prepared for a very ugly default experience. ;-)

**Comment by Renkoto** [comment]
> Hi there @deff245 , really glad to hear that it's working well for you!
> 
> Regarding reverting to the vanilla Debian theming, yep, it's pretty easy. Just delete `.config/xfce4` and `.config/dconf` from the home directory of the users. To prevent future new user accounts from picking up the SpiralLinux default theme you can also delete those same two directories from `/etc/skel/` as well.
> 
> Just be prepared for a very ugly default experience. ;-)

Hi, i would like to know how to make apps run as root match my user's theme. 
![Screenshot_20221019_001945](https://user-images.githubusercontent.com/69415770/196604087-31e4c908-2b01-4851-83c7-ce13eaf53246.png)
In some desktops this is easily fixable but in LXQt and KDE root apps always use the Numix theme.

**Comment by geckolinux** [comment]
@Renkoto Hi, you need to open the Plasma or LXQt settings as root and change the theme there.

**Comment by Renkoto** [comment]
> @Renkoto Hi, you need to open the Plasma or LXQt settings as root and change the theme there.
I've tried that and that doesn't seem to work, is there a preconfigured environment variable that's preventing that? in other desktop environments like GNOME and Xfce root apps recognize installed GTK themes, i switched to the Testing branch btw.

**Comment by CicadaSeventeen** [comment]
If you can download theme from kde store and install and use it?

**Comment by geckolinux** [comment]
This is how the the default SpiralLinux theming for a normal Plasma user gets applied to root applications as well during the ISO generation process:

```
### Make pkexec apps use the correct theme
cp -R /etc/skel/.config /root/
cp -R /etc/skel/.kde /root/
cp -R /etc/skel/.local /root/
cp /etc/skel/.gtkrc-2.0 /root/
```

So you could try to delete those files and directories from your `/root/` directory and then copy those same files from your normal user account back to `/root/` .

> in other desktop environments like GNOME and Xfce root apps recognize installed GTK themes

That's one of the biggest differences in Plasma and LXQt, it's extremely difficult to achieve theming consistency with Qt applications.

**Comment by Renkoto** [comment]
>So you could try to delete those files and directories from your `/root/ `directory and then copy those same files from your normal user account back to `/root/ `.

How exactly i do that?
also in the config folder there is much more than themes, so i don't know the directories/files that i have to paste there

Btw, i've noticed that when i install and choose a theme from the KDE Store the GTK root theme failback to Adwaita, but if i choose Breeze the theme changes to Numix even if i have uninstalled it.

**Comment by geckolinux** [comment]
Hi there, delete:
`/root/.config`
`/root/.kde`
`/root/.local`
`/root/.gtkrc-2.0`

> also in the config folder there is much more than themes, so i don't know the directories/files that i have to paste there

True, Plasma/KDE makes a huge mess of the `~/.config/` directory with all of its config files scattered all over the place. I'd say just copy everything and then delete from `/root/.config/` the directories that you recognize like `libreoffice` or whatever.

> when i install and choose a theme from the KDE Store the GTK root theme failback to Adwaita

That's right, another thing about running graphical applications as root is that they can't find themes installed into your user's home directory. They need to be installed system-wide in `/usr/share/themes/` .
