### ISSUE TITLE
lvm support problem

### ISSUE THREAD

**Issue by CicadaSeventeen** [SpiralLinux/SpiralLinux-project#169]
I have a partition on lvm in my SSD and it is the file of another Linux system. That system has problem to boot now so I need to mount it in SpiralLinux to get the file back.
However, I cannot find it in my `/dev/fedora_fedora`. It should be here. `gparted` cannot see it too, but I also install kde `partitionmanager` and after starting it, my partition become back.
![image](https://user-images.githubusercontent.com/86961676/196731465-fc9f867e-c8bb-4666-83f6-94d35fc66de1.png)
```
Only thing I do here is to start partitionmanager and my partition is back
```

**Comment by CicadaSeventeen** [comment]
I install `udisks2-lvm2` and it seems that such problem is solved. I need to confirm it.

**Comment by CicadaSeventeen** [comment]
I find out that the package that solve this problem is `thin-provisioning-tools`

**Comment by geckolinux** [comment]
OK, can you please just confirm that adding this package doesn't cause any other weird behavior, especially on normal systems without LVM?

**Comment by geckolinux** [comment]
Implemented in https://github.com/SpiralLinux/SpiralLinux-project/releases/tag/12.231001
