### ISSUE TITLE
r1868 dkms fails for 5.19 kernel from bullseye backports

### ISSUE THREAD

**Issue by CicadaSeventeen** [SpiralLinux/SpiralLinux-project#175]
bullseye backports have updated to kernel 5.19.
`r8168-dkms` from bullseye backports fails to build for 5.19
`r8168-dkms` from Sid needs higher version `dkms` so cannot just use it.
This is a bug for debian backports. Just write here as information.

**Comment by CicadaSeventeen** [comment]
https://bugs.launchpad.net/ubuntu/+source/r8168/+bug/1982000
The same bug from Ubuntu

**Comment by CicadaSeventeen** [comment]
> Thanks for the notification on this. Could you please report it to the Debian Backports mailing list with a link to the Ubuntu bug as well? https://lists.debian.org/debian-backports

I have sent a mail.
BTW, `r8168` is only needed when in-tree module `r1869` cannot work. Installing `r8168` will blacklisting `r8169`. So I am wondering if pre-install `r8168-dkms` is a good choice.

**Comment by CicadaSeventeen** [comment]
[r8168-temp.tar.gz](https://github.com/SpiralLinux/SpiralLinux-project/files/9895579/r8168-temp.tar.gz)
This package may work on 5.19. I have written to mailing list but they have not replied. I make this package myself and it does not report error on 5.19. However, I have no r8168 hardware to test

**Comment by CicadaSeventeen** [comment]
https://github.com/SpiralLinux/SpiralLinux-project/discussions/176
This is same problem.

**Comment by geckolinux** [comment]
https://github.com/SpiralLinux/SpiralLinux-project/issues/199
