### ISSUE TITLE
Error in the sound of the XFCE flavour

### ISSUE THREAD

**Issue by jk456789** [SpiralLinux/SpiralLinux-project#186]
I have used the XFCE flavour for more than one week and I found just a problem: when you enter in youtube you can not hear the sound of the videos. So you enter the sound settings and see that the problem is that the sound does not go through the headphones;: you put it right but apparently there is not any way to settle it permanently. Therefore every time you turn on the computer you have to do  the mending. I have seen that this does no happen in MInt or Manjaro, for example.

**Comment by geckolinux** [comment]
Hi there, unfortunately I don't think this can be fixed, as it's most likely an issue with the version of ALSA and PulseAudio in Debian Stable. I would recommend that you try both kernel versions in SpiralLinux to see if that makes any difference. You could also try replacing PulseAudio with Pipewire from Debian Backports.

**Comment by jk456789** [comment]
Thank you very much for the reply.
It is very strange: the problem happened  using a built computer with an
ASUS H81M-K motherboard. However if I install in that computer the XFCE
flavour of Mint or Manjaro does not happen. Then I changed to another
computer: an HP Elitedesk 800 G1 SFF and there is not problem with it. So I
am using Spiral Linux XFCE on that computer and it is all right.

**Comment by geckolinux** [comment]
Thanks for the response. Yes, it can be rather random. Lots of audio hardware has weird "quirks" for which Linux developers gradually implement workarounds. In this case it looks like the older components of Debian Stable don't have workarounds yet for your hardware.
