### ISSUE TITLE
How do I downgrade to kernel 5.19?

### ISSUE THREAD

**Issue by brakenow** [SpiralLinux/SpiralLinux-project#204]
And block kernel 6.0 when updating.

**Comment by geckolinux** [comment]
The previous 5.19 kernel shouldn't have been removed when you upgraded, and it should be available in GRUB.

If it works with your hardware I would suggest using the Debian Stable 5.10 kernel and removing the APT preference for the Backports version of the kernel.

**Comment by brakenow** [comment]
Thanks 😊

After a fresh install before upgrading one could execute:

sudo apt-mark hold linux-image-$(uname-r)

**Comment by geckolinux** [comment]
The previous kernels are also available for download, for example: `linux-image-5.19.0-0.deb11.2-amd64` .
