### ISSUE TITLE
Install xdg-utils by default on KDE Plasma spin

### ISSUE THREAD

**Issue by schmidthausen** [SpiralLinux/SpiralLinux-project#210]
Please add xdg-utils by default on the KDE Plasma spin. Lots of applications use this to open the default browser, etc.

**Comment by geckolinux** [comment]
Indeed, that is a bit of an omission, I'm not sure why it wasn't included already.

**Comment by geckolinux** [comment]
Implemented in https://github.com/SpiralLinux/SpiralLinux-project/releases/tag/12.231001
