### ISSUE TITLE
Include locales-all in default image (xfce)

### ISSUE THREAD

**Issue by RainmakerRaw** [SpiralLinux/SpiralLinux-project#211]
Running the XFCE version (XFCE_11.220925_x86-64), I noticed that I couldn't get powerline/ohmyzsh glyphs to render correctly in `xfce4-terminal`, despite having appropriate Nerd Fonts installed. I also had some other errors about locale settings every time I installed packages. 

I set and updated locales, both through `sudo dpkg-rconfigure locales` and the GUI tool provided, but none of the errors went away. After some searching, I found the solution. I had to install `locales-all` and then issue `sudo update-locale` again, and the errors went away. Please consider including `locales-all` as part of future images, this took me a while to track down! Thanks.

**Comment by geckolinux** [comment]
It looks like `locales-all` is not the solution. Please use the SpiralLinux language installation helper script.
https://github.com/SpiralLinux/SpiralLinux-project/releases/tag/12.231001
