### ISSUE TITLE
request Pantheon desktop

### ISSUE THREAD

**Issue by methanoid** [SpiralLinux/SpiralLinux-project#212]
I notice Geckolinux has Pantheon desktop option... could Spiral too?

Also Deepin and Cutefish look quite nice if we wanna go for "completeness"

I do wonder if a single ISO could just allow user to select the DE they want for their Spiral Linux (and Gecko too).

**Comment by geckolinux** [comment]
Hi there, thanks for the suggestions.

> I notice Geckolinux has Pantheon desktop option... could Spiral too?
> Also Deepin and Cutefish look quite nice if we wanna go for "completeness"

Unfortunately none of those are available in the Debian repositories.

> I do wonder if a single ISO could just allow user to select the DE they want for their Spiral Linux (and Gecko too).

No, that's not feasible, having multiple desktops installed causes all sorts of problems.
