### ISSUE TITLE
`grub-btrfs` currently broken in systems upgraded to Unstable/Sid due to upstream `btrfs-progs` change

### ISSUE THREAD

**Issue by geckolinux** [SpiralLinux/SpiralLinux-project#218]
https://github.com/Antynea/grub-btrfs/issues/254

Hopefully a fixed version will appear in Sid at some point. Meanwhile you can downgrade `btrfs-progs` to this version:
https://snapshot.debian.org/archive/debian/20221201T090253Z/pool/main/b/btrfs-progs/btrfs-progs_6.0.2-1_amd64.deb

**Comment by Draguljche** [comment]
Arch Linux already has it fixed... I hope Debian will have it soon...

**Comment by geckolinux** [comment]
Appears to be fixed now in Debian Sid.
