### ISSUE TITLE
Package format choice at install

### ISSUE THREAD

**Issue by Thatoo** [SpiralLinux/SpiralLinux-project#226]
It would be nice, at install, if we could choose which package format to use in SpiralLinux (Flatpak, Snap, Appimage ..) on top of apt and deb.

**Comment by geckolinux** [comment]
Hi there, thanks for the suggestion.

This won't be implemented, as Flatpak is already integrated and carefully configured for proper theming by default in SpiralLinux.

As for Snap apps, they do not integrate correctly with the desktop theme, there is no graphical frontend to install them, and a lot of potential SpiralLinux / Debian users are looking specifically for something different from Ubuntu that doesn't use Snap.

Regarding Appimages, there is nothing special to configure or enable in SpiralLinux if the user wants to run them. Simply download an Appimage, right-click on the file properties to make it executable, and then double-click it.

**Comment by Thatoo** [comment]
I agree for Flatpak and Snap but, for Appimages, it would be nice, if the user wants to use Appimages to dedicate a folder for Appimages like /home/USER/Appimages or /opt/Appimages and install AppImageLauncher.
