### ISSUE TITLE
[Cinnamon] Include MATE/X-Apps instead of Gnome apps

### ISSUE THREAD

**Issue by Azl-Eyekay** [SpiralLinux/SpiralLinux-project#227]
Hi,
Linux Mint ships X-Apps instead of Gnome apps in its Cinnamon edition which are more traditional looking and fit in well with the rest of the distro. Its Xed text editor is (sort of) based on MATE's Pluma, its PDF viwer is based on Atril etc. X-Apps aren't present on Debian but the MATE ones they are based on are and they look way better than the Gnome ones shipped out of the box. They don't depend that on that many new packages as well. So I suggest replacing the following Gnome apps in the Cinnamon image:

Pluma instead of Gedit as the text editor
Atril instead of Evince as the PDF viewer
eom (Eye of MATE) instead of eog (Eye of Gnome) as the image viewer
Mintstick (Linux Mint's USB image writer which is present on Debian) instead of MultiWriter (This package is only present in bookworm and onwards though, it may be suitable for when you make the bookworm images)

These look way better than the Gnome CSD apps in a traditional DE like Cinnamon.
Thanks for the awesome work!

**Comment by geckolinux** [comment]
Hi there, thanks a lot for the suggestions.

I wish the X-apps were available for Debian, I always liked Xed and their image viewer.

- **Pluma:** I'm pretty sure there's a reason why I didn't choose it, but it's worth revisiting for Bookworm.
- **EOM:** Same as above.
- **Atril:** Unfortunately Atril is missing the search feature in Evince where it lists all the results with a bit of context and allows skipping to a specific result by clicking on it. It has been [requested](https://github.com/mate-desktop/atril/issues/238) for Atril but it's not going anywhere fast.
- Mintstick: Thanks a lot for suggesting this, great news that it's going to be in Bookworm. Sounds like a strong candidate.

**Comment by Azl-Eyekay** [comment]
Hi, thanks for the quick response!
I did a quick side-by-side comparison of Pluma and eom with their Linux Mint counterparts, and they seem pretty much the same. So I hope you will take a look at it again.
As for Atril, I definitely see your point that the search function is much more primitive. So I guess users have to take a choice on whether we want a better app or a better looking app XD
Thanks again!

**Comment by geckolinux** [comment]
Do the Mate apps appear in your app menu outside of Mate? At least in the case of `mate-search-tool` it has an entry in the `.desktop` file that makes it not appear outside of Mate.

**Comment by Azl-Eyekay** [comment]
Hi,
As per my testing, Pluma, Atril and eom do show up in Cinnamon as well. Other MATE apps (caja, mate screenshot, mate sytem monitor) do not.

**Comment by alejandro097** [comment]
> 

you could just install them from their repo... http://packages.linuxmint.com/list-src.php?release=elsie that's how I got nemo and xed

**Comment by alejandro097** [comment]
> Hi, thanks for the quick response! I did a quick side-by-side comparison of Pluma and eom with their Linux Mint counterparts, and they seem pretty much the same. So I hope you will take a look at it again. As for Atril, I definitely see your point that the search function is much more primitive. So I guess users have to take a choice on whether we want a better app or a better looking app XD Thanks again!

you could just install them from their repo... http://packages.linuxmint.com/list-src.php?release=elsie that's how I got nemo and xed

**Comment by Azl-Eyekay** [comment]
@alejandro097 you have just made my day, I did not realise there was a Debian repo of Linux Mint. But I don't think adding a separate repo for just a single edition is something the dev would want to do

**Comment by geckolinux** [comment]
@Azl-Eyekay Right, I wouldn't include a 3rd party repo out-of-the-box, but I'm sure it would work well if you add it to your own installation.

**Comment by geckolinux** [comment]
Implemented in https://github.com/SpiralLinux/SpiralLinux-project/releases/tag/12.231001
