### ISSUE TITLE
Aorus Elite V2/Ryzen 5600 - boot failure/IRQ kernel panic

### ISSUE THREAD

**Issue by Xdavius** [SpiralLinux/SpiralLinux-project#245]
Hi.

2 days ago I have tried the distro in VM. Everything OK. I have tried in hard, and IRQ kernel panic...

Bad days for me. Tried the Debian testing installer: break before rebooting/freeze at synchronizing my devices. 

I'm in discussion with Nutyx creator to give my help. Same problem in hard. IRQ and kernel panic.

Both 5.10/5.18 from Spiral ISO falls.
But, I successfully installed Debian 11 with the live ISO kernel 5.10. 

On Nutyx, both 6.1/6.2 with same result.

I can boot on Ubuntu/Arch mainline/stable/lts. 

Known issue on my motherboard: enforce=lax is needed for RGB control.

I'm still searching to understand.

I have seen an other older issue on a Lenovo laptop.
With Nutyx on Lenovo : amd-VI error, iommu trouble in kernel. Still searching the good config. (Can be bypass by iommu=off)

Ok, thanks for reading all ! I still have hope to get Spiral working. And Nutyx too ...

**Comment by geckolinux** [comment]
Please reopen if the issue persists in https://github.com/SpiralLinux/SpiralLinux-project/releases/tag/12.231001
