### ISSUE TITLE
Plasma Dolphin file manager details tab missing

### ISSUE THREAD

**Issue by banzaigtv** [SpiralLinux/SpiralLinux-project#278]
When I go to the properties of a media file, the details tab is missing. This is not an issue with any other distro I have tested. Images below illustrate this. This image is SpiralLinux KDE with the details tab missing:
![Screenshot from 2023-06-29 08-16-53](https://github.com/SpiralLinux/SpiralLinux-project/assets/80161570/96eb5529-d9b8-400b-998c-7c9000e142e8)

This image is Debian 12 KDE with the details tab present:
![Screenshot from 2023-06-29 08-18-45](https://github.com/SpiralLinux/SpiralLinux-project/assets/80161570/110b236e-0acb-41a2-a2ee-4432fde50ffa)

**Comment by geckolinux** [comment]
Hi there, thanks for the helpful report. Please install the package `libkf5baloowidgets-bin` . This will be included by default in the next SpiralLinux release.

**Comment by banzaigtv** [comment]
That fixed it. Thank you. Now there should be no issues if I decide to reinstall the distro with the Plasma desktop and Debian 12 base.

**Comment by geckolinux** [comment]
Implemented in https://github.com/SpiralLinux/SpiralLinux-project/releases/tag/12.231001
