### ISSUE TITLE
Caps Lock

### ISSUE THREAD

**Issue by Poverest** [SpiralLinux/SpiralLinux-project#286]
Spiral Gnome (latest) + Brave Browser

Cap Lock not work (light not even coming on).
Rebooted with another distro USB and it works fine.
Everything else works OK (1-year-old pc).
Not sure if it's a spiral or brave bug at this point.

**Comment by geckolinux** [comment]
https://github.com/SpiralLinux/SpiralLinux-project/wiki#faqs
