### ISSUE TITLE
Mention new "non-free-firmware" repo in "upgrade instuctions" 

### ISSUE THREAD

**Issue by xalt7x** [SpiralLinux/SpiralLinux-project#291]
I've  tried to upgrade "Spiral Linux 11 XFCE" to "Debian 12" base following Wiki instruction "[Updating and upgrading SpiralLinux](https://github.com/SpiralLinux/SpiralLinux-project/wiki#updating-and-upgrading-spirallinux)".
However during dist-upgrade I've noticed that Apt wants to delete "atheros-firmware" package

![image](https://github.com/SpiralLinux/SpiralLinux-project/assets/44649402/416996ee-c337-465d-845b-22c19dc32ede)

Turns out this package moved from "non-free" to "non-free-firmware"
So for a better upgrade user needs to modify
"Debian stable (for upgrades)" item
adding "non-free-firmware"

![image](https://github.com/SpiralLinux/SpiralLinux-project/assets/44649402/6cec510e-0f2b-473d-8600-8943f0b18552)

After that upgrade will be more smooth

![image](https://github.com/SpiralLinux/SpiralLinux-project/assets/44649402/7e9e1081-2830-42c7-a24b-d91993c6fb54)

**Comment by geckolinux** [comment]
Great idea, thanks, I just added it for https://github.com/SpiralLinux/SpiralLinux-project/releases/tag/12.231001
