### ISSUE TITLE
Bullseye or Bookworm? 

### ISSUE THREAD

**Issue by Tockiri** [SpiralLinux/SpiralLinux-project#296]
lsb_release -a and inxi both show "Debian Bookworm" while package sources still show Bullseye: The package sources (i.e., the sources.list file) still point to the Bullseye repositories. Ist this a bug?

**Comment by geckolinux** [comment]
Hi there, have you attempted to upgrade your installation to Bookworm?
Please post your `/etc/apt/sources.list` and all files under `/etc/apt/sources.list.d/` , also looking for backup old versions of files with suffixes like `.save` .

**Comment by Tockiri** [comment]
Thanks for your help. No, I have not upgraded to Bookworm.

/etc/apt/sources.list:

> deb http://deb.debian.org/debian/ bullseye main contrib non-free
#deb-src http://deb.debian.org/debian/ bullseye main contrib non-free
deb http://security.debian.org/ bullseye-security main contrib non-free
#deb-src http://security.debian.org/ bullseye-security main contrib non-free
deb http://deb.debian.org/debian/ bullseye-updates main contrib non-free
#deb-src http://deb.debian.org/debian/ bullseye-updates main contrib non-free
deb http://deb.debian.org/debian/ bullseye-backports main contrib non-free #Debian Bullseye Backports'

-----
/etc/apt/sources.list.d:

home_bgstack15_aftermozilla.sources 
home-ungoogled_chromium.list        
home-ungoogled_chromium.list.save  
librewolf.sources   
spirallinux.list                 
spirallinux.list.save

Is it that what you mean?

**Comment by geckolinux** [comment]
Hi there, you might also want to check the contents of all those files in `/etc/apt/sources.list.d/` to see if any of them are referencing Bookworm. It's not possible for the system to upgrade itself without being explicitly told to do so.

**Comment by Tockiri** [comment]
The point is why lsb_release -a and inxi both show "Debian Bookworm" while package sources still show Bullseye - so far.

**Comment by geckolinux** [comment]
You are indeed running Bookworm, the real question is who / what performed the upgrade.
