### ISSUE TITLE
grub? error

### ISSUE THREAD

**Issue by thebestcloudislocal** [SpiralLinux/SpiralLinux-project#301]
Hello,

I recently "aptitude full-upgrade"d a Sid installation. I remember that a new kernel was installed and that snapshots were listed, I suppose this list was related to grub.

After booting the usual grub password ask dialog appears. It's possible to enter the password and slot opened appears, immediately followed by a reboot into the main board UEFI. I guess that's just the boot order.

Can you tell me how I could mount @home with an USB Linux, so that I could "rsync -av" my current /home folder (not a snapshot) to an external hard disk?

Also, is it easily possible to repair grub (I guess it's a grub error)?

Thanks in advance for any help you can provide!

**Comment by geckolinux** [comment]
https://github.com/orgs/SpiralLinux/discussions/303#discussioncomment-6992000
