### ISSUE TITLE
Inconsistent gtk4/libadwaita Apps through flatpak in SpiralLinux 12 Budgie Editions

### ISSUE THREAD

**Issue by Reno-Sifana** [SpiralLinux/SpiralLinux-project#309]
Hello. I'm Have Problem with gtk4/libadwaita Apps i installed through flatpak. (Wrong Theme in Title Bar) 
![Snapshot_2023-10-03_14-06-43](https://github.com/SpiralLinux/SpiralLinux-project/assets/68702583/8b084b7d-ec3e-4073-b36f-efdf1a402380)
The Interface should look like this 
![image](https://github.com/SpiralLinux/SpiralLinux-project/assets/68702583/0946e411-ffdd-49cc-91a0-2bbd7bd84185)

**Comment by geckolinux** [comment]
Hi there, it looks like the developers of that app have updated it to ignore all of the limited environment variables that GTK4 and libadwaita respect. I tested it in SpiralLinux Gnome and in Linux Mint, and it looks exactly the same.

![Screenshot from 2023-10-04 09-59-28](https://github.com/SpiralLinux/SpiralLinux-project/assets/2692138/de97513f-ea57-414c-bf1b-207d6c2296bf)

In SpiralLinux Budgie you can test other DEB packaged and Flatpak installed GTK4 / libadwaita apps like Gnome Software, Gradience, and Flatseal to see how they should normally look with the limited amount of customization that I was able to include for GTK4 / libadwaita in SpiralLinux.
