### ISSUE TITLE
Gnome: Setting wallpaper from nautilus failed

### ISSUE THREAD

**Issue by fredg0** [SpiralLinux/SpiralLinux-project#312]
Hi,

Right clicking on an image in nautilus and choosing "set as wallpaper" does nothing.

Installing "xdg-desktop-portal-gnome" fixed the issue.

Best regards.

++

**Comment by geckolinux** [comment]
Hi @fredg0 , nice catch! Thanks for letting me know, that package seems to have escaped me for some reason. Just in time before I generate the next release to fix a few papercuts like this.

**Comment by geckolinux** [comment]
Fixed in the 12.231005 release.
