### ISSUE TITLE
Remove raspi-firmware

### ISSUE THREAD

**Issue by mlcarson** [SpiralLinux/SpiralLinux-project#315]
On a new install of the nvidia-driver, there was a z50-raspi-firmware file in the /etc/initramfs/postupdate.d directory which prevented the update-initramfs from finishing properly because it was searching for firmware which didn't exist.  This was on an AMD64 (Ryzen 5700G) system.   Deleting the z50-raspi-firmware script fixed the problem.

**Comment by geckolinux** [comment]
Appreciate the tip, I'll see if I can remove that firmware package from the next set of ISOs.

**Comment by mlcarson** [comment]
Just to be clear, the firmware didn't exist.  That's why the script failed.  The script itself shouldn't be there as a post update script when the target device is not a raspberry pi.

**Comment by geckolinux** [comment]
Oops, sorry, so it's a script and not a package. But from what I can tell the `z50-raspi-firmware` script is provided by the [raspi-firmware](https://packages.debian.org/bookworm/raspi-firmware) package. So by either uninstalling that package during the ISO creation process or including an APT rule to prohibit its installation it looks like this problem could be avoided, correct?

Also, from [this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1053120#26) (unrelated) bug report I understand that they're getting ready for the next Debian point release very soon, and I suspect they'll probably fix this issue too.

**Comment by mlcarson** [comment]
That's what I suspect but I am no expert.  I just happened to be doing a new deployment today and tried the SpiralLinux Plasma version and encountered it.  It's my only system with an Nvidia card and it was a clean install so figured I'd report the issue.

**Comment by geckolinux** [comment]
Fixed in this release:
https://github.com/SpiralLinux/SpiralLinux-project/releases/tag/12.231008
