### ISSUE TITLE
Blank screen with underscore, no boot

### ISSUE THREAD

**Issue by piyushpaliwal** [SpiralLinux/SpiralLinux-project#327]
I just tried installing SpiralLinux on my PC. The install finishes fine but upon trying to boot, it gets stuck at blank screen with an underscore on it. I can't switch to console as well, basically leaving no other option but to do a hard restart.

As for my setup, I am running Windows alongside on a separate physical ssd. I have a Nvidia graphics card (RTX 3070).

Would you be able to help out on this?

**Comment by geckolinux** [comment]
Hi, did you try booting with both kernels? Did you try the failsafe boot options?

**Comment by piyushpaliwal** [comment]
After trying with kernel 6.1, it worked; however, with the 6.4 kernel it errors out.
I don't know what failsafe mode does, will read about it and can try that as well.

**Comment by geckolinux** [comment]
OK, thanks for confirming. You can remove the `/etc/apt/preferences.d/99backports` file and uninstall the 6.4 kernel.
