### ISSUE TITLE
Fingerprint reader support KDE

### ISSUE THREAD

**Issue by Rik44444** [SpiralLinux/SpiralLinux-project#336]
Hi,
apologies if this is not the right place to ask questions. 
I will be installing a new distro with KDE soon and am considering SpiralLinux. Does the KDE version provide fingerprint login support by default? This is currently the only negative I've been able to find on KDE as compared to Gnome, it does not support fingerprint logins well (tried on Kubuntu and KDE neon). It would be great if this SpiralLinux KDE did support it (perhaps easier because it is based on Debian instead of Ubuntu?)
If not available could I submit it as a feature request? 
Thanks
Rik
PS i've heard some people argue that fingerprint support is not important but it is not so secure, but I am on the train a lot, for me typing in my password all the time is less secure.

**Comment by geckolinux** [comment]
Hi there, I'm pretty sure it won't be supported. But you can test it on your hardware with the live CD, just add a password to the live system `linux` user account and log out.

**Comment by Rik44444** [comment]
👍 ok thanks will do. If you ever discover why ubuntu has this working by default in its user profile settings and kde does not and find a way to add it to the kde SL release, that'd be amazing :). 
Thanks for your work on this!
