### ISSUE TITLE
The English us keyboard layout is incorrect

### ISSUE THREAD

**Issue by NektoNektovich** [SpiralLinux/SpiralLinux-project#340]
The English us keyboard layout is incorrect - instead of the letter "p" - "/" is typed, and choosing any other layout does not correct the situation. There is also a similar error in: peppermint 12, solydx 12, but in the original debian 12 xfce live iso and in emmabuntus there is no such problem.

**Comment by geckolinux** [comment]
Hi there, that's definitely not a general problem with English keyboards on those distros, as I and many other English speakers use the same layout with no issues.

Please post 1) a photo of your keyboard, 2) a screenshot of your desktop environment's keyboard layout configuration (you didn't mention which version you're using), and 3) the content of `/etc/default/keyboard` .

**Comment by NektoNektovich** [comment]
> Hi there, that's definitely not a general problem with English keyboards on those distros, as I and many other English speakers use the same layout with no issues.
> 
> Please post 1) a photo of your keyboard, 2) a screenshot of your desktop environment's keyboard layout configuration (you didn't mention which version you're using), and 3) the contents of `/etc/default/keyboard` .
[keyboard.txt](https://github.com/SpiralLinux/SpiralLinux-project/files/13125272/keyboard.txt)
![20231024_191032](https://github.com/SpiralLinux/SpiralLinux-project/assets/53621368/5769fdda-87c9-42ac-a52b-d1fdf4c0cf63)
![Screenshot_2023-10-24_21-07-17](https://github.com/SpiralLinux/SpiralLinux-project/assets/53621368/25603c13-8cdd-4971-82d8-abe97a983f6d)

**Comment by geckolinux** [comment]
Thanks for the images.
It looks like the number lock is activated. Did you try `Fn`+`Insert` to disable the `NumLK` function?

**Comment by NektoNektovich** [comment]
> Thanks for the images. It looks like the number lock is activated. Did you try `Fn`+`Insert` to disable the `NumLK` function?

no.

**Comment by geckolinux** [comment]
OK, can you please try that?

**Comment by NektoNektovich** [comment]
> OK, can you please try that?

Of course I'll try it tomorrow and let you know👌

**Comment by NektoNektovich** [comment]
> OK, can you please try that?

It works, thanks!
