### ISSUE TITLE
enhancement: clamaris installer: change grub destination according to insall location/device

### ISSUE THREAD

**Issue by g6094199** [SpiralLinux/SpiralLinux-project#343]
hi,

while installing on systems with more than one block device you need to select to install destination for debian. When changed from the by default chosen device to another it would be VERY handy that the grub install destination would also switch to the chooses device, cause in most cases the chosen device should hold grub, too.

i attached a hdd via dock to a laptop and booted the installer via usb stick. spiral should be installed to the dock located hdd. in a hurry i forgot to change to grub location an grilled my windows bootloader on the laptops internal drive, cause this was the default location while drive detection in calamares. this was anoying but not to terrible to fix. but just a waste of time. ;-)

**Comment by geckolinux** [comment]
Hi, this would be a feature request for the Calamares project.
