### ISSUE TITLE
spiral budgie: alt + tab doesnt show all aktive programs

### ISSUE THREAD

**Issue by g6094199** [SpiralLinux/SpiralLinux-project#366]
since install alt + tab doesnt show all active programs which makes switching a nightmare!

![grafik](https://github.com/SpiralLinux/SpiralLinux-project/assets/37833326/68da0e00-befe-4dc6-adef-4cbb158769fb)

as you can see 2 switchable programs (ff, arduino ide) are shown while  LO, calc,  pdf viewer....are not switchable. thats very annoying and makes my hair go gray/white.

**Comment by geckolinux** [comment]
Hi there, I'm honestly not too sure if that can be changed. Are the other windows on a different workspace?

In general SpiralLinux can only change the default behavior via its default configuration, but any change that requires modifying the source code or repackaging it is out of the scope of the project.

**Comment by g6094199** [comment]
ola.

> Are the other windows on a different workspace?

no. i dont use this concept. it just messes things more up.

> Hi there, I'm honestly not too sure if that can be changed.

so why is it working in ubuntu for years (ever)? so this MUST be a bug somewhere.

**Comment by geckolinux** [comment]
There could definitely be a bug, but you would have to report it to Debian, and they generally don't fix non-critical bugs within the stable release lifecycle.
