### ISSUE TITLE
The Reddit sticky post redirects to Gecko Linux instead of Spiral Linux GitHub 

### ISSUE THREAD

**Issue by gabriele-3** [SpiralLinux/SpiralLinux-project#37]
Hi there Sam. 

I'm referring to this Reddit post:

https://www.reddit.com/r/SpiralLinux/comments/vkfb40/please_use_the_official_spirallinux_forum_on/

The subject fully describes the issue.

**Comment by geckolinux** [comment]
Oops, good catch, fixed now. Thanks!
