### ISSUE TITLE
USB Stops working after 30 seconds or so

### ISSUE THREAD

**Issue by manujchandra** [SpiralLinux/SpiralLinux-project#375]
Hi, 

I am using SpiralLinux_XFCE_12.231008_x86-64.iso. I installed in on an HP AMD APU Laptop and then upgraded the system. It's a fresh installation.

When I log in, the USB mouse and HDD are working. After 30 seconds, they get disconnected. I have rebooted and tried 2-3 times.

Any idea what might be causing this?

Thanks in advance.

**Comment by geckolinux** [comment]
Hi there, does it behave differently with the latest 6.5 kernel (after you upgraded) compared to the 6.4 kernel from the original installation as well as the 6.1 kernel?

If the behavior is consistent across the kernels then try temporarily disabling the power saving profile:
`sudo systemctl disable tlp`

**Comment by manujchandra** [comment]
Hi,

1) I disabled tlp as sudo systemctl disable tlp
Rebooted
Tried again did not work

2) I installed SpiralLinux_XFCE_12.231120_x86-64.iso
sudo apt update && sudo apt upgrade
Did not work
I disabled tlp as sudo systemctl disable tlp
Rebooted
Tried again did not work

3) I installed SpiralLinux_XFCE_12.231120_x86-64.iso
Connected laptop to power source
sudo apt update && sudo apt upgrade
Did not work
Uninstalled tlp sudo apt remove tlp
Rebbot
USB worked as expected.

Summary:
Uninstalling tlp made the USB ports work with laptop running on battery and power. 

Is there a way to keep tlp and USB ports enabled at the same time?

**Comment by geckolinux** [comment]
Hi there, yes, you can edit the TLP configuration in `/etc/tlp.conf` with the root file editor option. The easiest change would probably be to change:
`#USB_AUTOSUSPEND=1`
to
`USB_AUTOSUSPEND=0`

If you really wanted to you could get fancy and get the ID of specific USB controllers and add them to the blacklist so they don't get automatically suspended, but it's probably not worth the effort.
