### ISSUE TITLE
No Wayland

### ISSUE THREAD

**Issue by STeX1389** [SpiralLinux/SpiralLinux-project#384]
I noticed that there is no wayland session in both gnome and kde on Spiral Linux (nor I found the packages that will enable it). Is there a way to enable wayland?

**Comment by geckolinux** [comment]
Hi there, Wayland is not officially supported or recommended for the SpiralLinux configuration. However, to the extent that Wayland works in Debian 12 it will also work in SpiralLinux.

For Gnome:
https://github.com/orgs/SpiralLinux/discussions/316#discussioncomment-7215164

For KDE I have no idea how, but I read that there is a package for Debian 12 that provides a Plasma session on Wayland.
