### ISSUE TITLE
Recommendations for installing packages

### ISSUE THREAD

**Issue by holton-jiang** [SpiralLinux/SpiralLinux-project#387]
Recommendations for Cinnamon Desktop:To remove redundant packages.
- 1.shotwell replaces eom
- 2.gnome-system-monitor replaces htop
- 3.geary replaces thunderbird, Because Thunderbird doesn't meet simplicity and deviates from the original purpose of SpiralLinux.

---

Recommendation for Builder: Add a graphical file manager, such as Nemo.

**Comment by geckolinux** [comment]
Hi there, thanks for the suggestions.

1. Shotwell provides basic editing capabilities, whereas EOM is a much faster quick image viewer, so both have different purposes.
2. `htop` is a very small terminal application that most users prefer. I don't like that it has an app menu entry, but that's the way Debian is. I suppose I could include a `.desktop` file to hide it from the menu, but I don't think it's worth the trouble.
3. All editions of SpiralLinux include Thunderbird on purpose as a recommendation for SpiralLinux users that might not know which mail app to choose. Of course users that have a different preference can uninstall Thunderbird and install whatever they like.

> Recommendation for Builder: Add a graphical file manager, such as Nemo.

Users that attempt to use the Builder edition should know how to install the graphical file manager of their choice. Notice that the graphical Synaptic package manager is pre-installed for doing so. The purpose of the Builder edition is _not_ to be usable out-of-the-box, but rather as a base for users that already know which GUI packages they want and how to configure them.
