### ISSUE TITLE
Cannot find cracklib-check

### ISSUE THREAD

**Issue by manujchandra** [SpiralLinux/SpiralLinux-project#394]
Hi,

I want to use the command cracklib-check. Its available in the Debian repo:

https://manpages.debian.org/bookworm/cracklib-runtime/cracklib-check.8.en.html
https://www.cyberciti.biz/security/linux-password-strength-checker/
https://linuxhint.com/check-password-strength-cracklib-check-raspberry-pi/
https://command-not-found.com/cracklib-check

I have installed:
cracklib-runtime
libcrack2

When I run :
`echo "password" | cracklib-check`

It says command not found :
`bash: cracklib-check: command not found`

Thanks.

**Comment by geckolinux** [comment]
Hi there, it gets installed to `/sbin/` which is not included in the default `$PATH` variable, so you need to run it as `/sbin/cracklib-check` .
