### ISSUE TITLE
Spiral Linux on EeePC 1215N

### ISSUE THREAD

**Issue by zcatav** [SpiralLinux/SpiralLinux-project#402]
Hi,
My netbook has following spesification:

> System:
>   Host: lmde Kernel: 6.1.0-18-amd64 arch: x86_64 bits: 64 Desktop: Cinnamon
>     v: 6.0.4 Distro: LMDE 6 Faye
> Machine:
>   Type: Laptop System: ASUSTeK product: 1215N v: x.x
>     serial: <superuser required>
>   Mobo: ASUSTeK model: 1215N v: x.xx serial: <superuser required>
>     BIOS: American Megatrends v: 0902 date: 05/05/2011
> Battery:
>   ID-1: BAT0 charge: 17.3 Wh (38.6%) condition: 44.8/47.5 Wh (94.2%)
>     volts: 11.2 min: 10.8
> CPU:
>   Info: dual core model: Intel Atom D525 bits: 64 type: MT MCP cache:
>     L2: 1024 KiB
>   Speed (MHz): avg: 1800 min/max: N/A cores: 1: 1800 2: 1800 3: 1800 4: 1800
> Graphics:
>   Device-1: Intel Atom Processor D4xx/D5xx/N4xx/N5xx Integrated Graphics
>     driver: i915 v: kernel
>   Device-2: NVIDIA GT218M [ION 2] driver: nouveau v: kernel
>   Device-3: IMC Networks UVC VGA Webcam type: USB driver: uvcvideo
>   Display: x11 server: X.Org v: 1.21.1.7 with: Xwayland v: 22.1.9 driver: X:
>     loaded: intel,modesetting unloaded: fbdev,vesa dri: i915 gpu: i915
>     resolution: 1366x768~60Hz
>   API: OpenGL v: 2.1 Mesa 22.3.6 renderer: i915 (: Pineview G)
> Audio:
>   Device-1: Intel NM10/ICH7 Family High Definition Audio driver: snd_hda_intel
>   Device-2: NVIDIA High Definition Audio driver: snd_hda_intel
>   API: ALSA v: k6.1.0-18-amd64 status: kernel-api
>   Server-1: PipeWire v: 0.3.65 status: active
> Network:
>   Device-1: Qualcomm Atheros AR8152 v2.0 Fast Ethernet driver: atl1c
>   IF: enp2s0 state: down mac: f4:6d:04:bb:ea:8d
>   Device-2: Broadcom BCM4313 802.11bgn Wireless Network Adapter driver: wl
>   IF: wlp3s0 state: unknown mac: e0:b9:a5:30:43:c4

I'm trying to install spiral Linux but system hang up at GPU driver level. My device has not option to switch between Intel i915 and  NVIDIA GT218M [ION 2]. Linux Mint Debian Edition 6 and Ubuntu 22.04 can work but Spiral Linux.
I prefer Spiral Linux to install. Is it possible?
Thanks.

**Comment by geckolinux** [comment]
Hi there, please try booting the SpiralLinux live system with both kernels (6.5 and 6.1 are both included).

**Comment by zcatav** [comment]
During the login process I opened options with tab and selected vmlinuz and initrd files. Both 6.1 and 6.5 failed respectively. The failsafe option also fails. I guess I will not be able to run Spiral Linux on this device.
Are there any other options I can try?
Thank you.

**Comment by geckolinux** [comment]
Hi there, it's hard to know without details about the error or what isn't working.

**Comment by zcatav** [comment]
I installed LMDE 6.
Solved.
