### ISSUE TITLE
ZFS support

### ISSUE THREAD

**Issue by danboid** [SpiralLinux/SpiralLinux-project#406]
I discovered SpiralLinux yesterday and my initial impressions are very good. I was inspired to try it out after noticing a post you made to grub-btrfs issues that you've had the good sense to include grub-btrfs and snapper by default which I think all x86 Linux OSs should install when you format using BTRFS, which shoud be the default, otherwise you might as well stick with XFS.

So now I'm stuck with recommending SpiralLinux for single disk Debian BTRFS installs and Proxmox-VE for those who want to use ZFS / software RAID because BTRFS RAID support is useless and ZFS has much better performance. I would love to see the Calamares / SpiralLinux installer improved so that we can install directly to mirrored, RAIDZ and RAIDZ2 ZFS pools then I would only need to recommend one version of Linux for everyone.

If ZFS support did get added , it would be good to also duplicate the special way that PVE installs GRUB so that you can boot off any disk in your ZFS pool in case any of them fail. This works for both UEFI and BIOS installations.

I realise that ZFS support could well be out of scope or too much work to add but if you don't ask you don't get.

Thanks!

**Comment by geckolinux** [comment]
Hi there, thanks for the suggestion. I would also strongly prefer ZFS support, but I don't think it's feasible given that SpiralLinux is built around GRUB for the broadest support of different BIOS / EFI environments as well as the user's choice of filesystem. In order to offer snapshot boot environments it would require integrating https://zfsbootmenu.org, which in turn requires a different bootloader, all of which would require a lot of custom scripting within Calamares that would probably be less reliable. You can see an overview of the challenges here:
https://github.com/calamares/calamares/issues/1947
I'll close this request for now as `cantfix`, but anybody who has a concrete suggestion of how to implement this is welcome to post it here.

**Comment by Ticklezz** [comment]
> Hi there, thanks for the suggestion. I would also strongly prefer ZFS support, but I don't think it's feasible given that SpiralLinux is built around GRUB for the broadest support of different BIOS / EFI environments as well as the user's choice of filesystem. In order to offer snapshot boot environments it would require integrating https://zfsbootmenu.org, which in turn requires a different bootloader, all of which would require a lot of custom scripting within Calamares that would probably be less reliable. You can see an overview of the challenges here: [calamares/calamares#1947](https://github.com/calamares/calamares/issues/1947) I'll close this request for now as `cantfix`, but anybody who has a concrete suggestion of how to implement this is welcome to post it here.

I wish Linus would just find out how to get this in the kernel. It's such a great file system.

**Comment by danboid** [comment]
Unfortunately Sun picked a license that was intentionally not GPL / Linux compatible and both Linus and Greg KH have an irrational hatred of ZFS. Reading comments they've made about it, they clearly know almost nothing about ZFS or its features, they just know about its anti-Linux license. Sun being bought by Oracle likely didn't help matters either.

I wouldn't wait for this to ever change. People have been hoping for that license change for at least a decade and Oracle do not seem to be bothered about it. They sell their own Linux distro so it would surely be in their interest to do that but I think this is Linus hating ZFS mainly. Maybe if Linus wanted it to happen it would?

**Comment by Ticklezz** [comment]
> Unfortunately Sun picked a license that was intentionally not GPL / Linux compatible and both Linus and Greg KH have an irrational hatred of ZFS. Reading comments they've made about it, they clearly know almost nothing about ZFS or its features, they just know about its anti-Linux license. Sun being bought by Oracle likely didn't help matters either.
> 
> I wouldn't wait for this to ever change. People have been hoping for that license change for at least a decade and Oracle do not seem to be bothered about it. They sell their own Linux distro so it would surely be in their interest to do that but I think this is Linus hating ZFS mainly. Maybe if Linus wanted it to happen it would?

Yeah I've read all the articles and the stupid licensing.  It's all up to Linus finding out how to make it work if he wanted. He doesn't want to so it will never happen.  Getting past the not GPL makes it where only Ubuntu has the balls to ship ZFS with it's distro. They really give zero fucks. It's just such a shame as it's so solid even on root. BSD uses it on root and it works so smoothly. ZFS bootmenu working with debian out of the box is all just dreams.
