### ISSUE TITLE
build no longer working 

### ISSUE THREAD

**Issue by souhaiebtar** [SpiralLinux/SpiralLinux-project#419]
hello @geckolinux, thanks again for your great work, i was able to build many time

`apt install live-build unzip nginx qemu-system-x86 patch`
than i unzip the the archive
than `./spiral -i`, i was able to build many time
but now it's no longer working

at the end it says 
```
mv: cannot stat 'live-image-amd64.packages': No such file or directory
mv: cannot stat 'live-image-amd64.hybrid.iso': No such file or directory
```

**Comment by geckolinux** [comment]
Hi there, please check toward the end of the complete log for details about what exactly is failing. I don't remember the exact location of the log file, but it's printed there in the terminal output.

**Comment by souhaiebtar** [comment]
@geckolinux i already checked, the `build.log` file is in the root directory (the same directory that contain `spiral` script),

but it only say 
```
E: Essential packages were removed and -y was used without --allow-remove-essential.
E: An unexpected failure occurred, exiting...
P: Begin unmounting filesystems...
P: Saving caches...
Reading package lists...
Building dependency tree...
Reading state information...
```

when i run `lb build --verbose`

i got 

```
Reading package lists...
W: GPG error: https://fasttrack.debian.net/debian-fasttrack bookworm-fasttrack InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C47F8A8AAD743EF7
E: The repository 'https://fasttrack.debian.net/debian-fasttrack bookworm-fasttrack InRelease' is not signed.
W: GPG error: https://fasttrack.debian.net/debian-fasttrack bookworm-backports-staging InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C47F8A8AAD743EF7
E: The repository 'https://fasttrack.debian.net/debian-fasttrack bookworm-backports-staging InRelease' is not signed.
E: An unexpected failure occurred, exiting...
P: Begin unmounting filesystems...
```

----

i also tried to run the script on `debian12` , the script create the iso file, i can boot into it and select an element in the grub  but when it come to interact with the UI (using mouse or keyboard ) to launch the installer i can't

i tried the iso on `Virtualbox`, also `kvm` but the same problem,

----

now  i returned to debian11, i added `--verbose` to `lb` commands in `spiral` script

now i have

```
lb clean --verbose
lb config --verbose
lb build   --verbose
```

even with `--verbose`

i get the same error

```
The following packages will be REMOVED:
  grub-efi-amd64-signed* mokutil* shim-helpers-amd64-signed* shim-signed*
  shim-signed-common* shim-unsigned*
WARNING: The following essential packages will be removed.
This should NOT be done unless you know exactly what you are doing!
  grub-efi-amd64-signed
0 upgraded, 0 newly installed, 6 to remove and 0 not upgraded.
E: Essential packages were removed and -y was used without --allow-remove-essential.
E: An unexpected failure occurred, exiting...
P: Begin unmounting filesystems...
P: Saving caches...
Reading package lists...
Building dependency tree...
Reading state information...
```
#### Update
 creating the iso does work under debian 12 (bookworm) and debian 13 (testing) but not under debian12 (bullseye), 
my last test was to build the xfce version under debian13 (testing) and i was able to install it on KVM (using UEFI firmware),

the same iso is not working (UI not responding when i arrive to the desktop) when i run it under KVM (using BIOS firmware).
the older images built under debian11 (when build was still working), i think supported the two type of firmware

**Comment by geckolinux** [comment]
Hi there,

The issue with the UI not responding when built with Debian 12 is a known issue. It has something to do with the Backports kernel. For that reason I also build the official SpiralLinux ISOs with Debian 11.

When attempting with a Debian 11 build system please attach your entire failed `build.log`. Thanks.

**Comment by souhaiebtar** [comment]
@geckolinux, i already removed it, i will launch the build another time on debian11 and i will put the `build.log`

**Comment by souhaiebtar** [comment]
@geckolinux

those are the last lines in the terminal

```
E: Essential packages were removed and -y was used without --allow-remove-essential.
E: An unexpected failure occurred, exiting...
P: Begin unmounting filesystems...
P: Saving caches...
Reading package lists...
Building dependency tree...
Reading state information...
mv: cannot stat 'live-image-amd64.hybrid.iso': No such file or directory
root@bullseye:/home/vagrant/SpiralLinux-Gnome# cp build.log /vagrant/
```
and this is the entire `build.log`
  
[build.log](https://github.com/SpiralLinux/SpiralLinux-project/files/14825073/build.log)

**Comment by geckolinux** [comment]
Thanks. It looks like these help reach the explanation:
- https://github.com/elementary/os/issues/514#issuecomment-892060669
- https://salsa.debian.org/live-team/live-build/-/merge_requests/255

Maybe try this, adapted from [here](https://github.com/ubuntucinnamon/iso-builder-devel/blob/master/live-build-fix-shim-remove.patch):
`PRE_APT_OPTIONS="${APT_OPTIONS}" APT_OPTIONS="${APT_OPTIONS} --allow-remove-essential" ./spiral`

**Comment by souhaiebtar** [comment]
@geckolinux i did try the command that you did give and the build finish,
but you need to change it to

```bash
PRE_APT_OPTIONS="${APT_OPTIONS}" APT_OPTIONS="${APT_OPTIONS} -y --allow-remove-essential" ./spiral
```
so that it confirm package installation automatically

**Comment by souhaiebtar** [comment]
@geckolinux sorry if if i'm taking a lot of your time, i did try to include some deb by default, `vscodium` if you know it, i did create a folder `packages` and `packages.chroot` inside `config` folder, and i even did update `config/package-lists/spirallinux-Gnome-pacakages.list.chroot` with the name of the packages but they won't install

**Comment by geckolinux** [comment]
Hi there. The path that I have tested to work for including additional DEB packages is `config/packages/` . You can check the `build.log` to see why it's not being installed, maybe it's a missing dependency.

**Comment by souhaiebtar** [comment]
> Hi there. The path that I have tested to work for including additional DEB packages is `config/packages/` . You can check the `build.log` to see why it's not being installed, maybe it's a missing dependency.

i didn't work, anyway now the build works so i think i can close a ticket, if you find the time can you please try again with a package like `pulsar editor` or `Vscodium' if you can install them when building the image.

For now i'm invistigating and testing`https://github.com/nodiscc/debian-live-config`  if it does support  adding `.DEB` and if  it does i will try to copy how it's done to your repo, thank you again,

really this image bring something very important by default which is rollback/snapshot with ease of access on Grub,

i will try to update the ReadMe and create a pull request to make it easier for others to build upon your work and customize their image
