### ISSUE TITLE
installation failure with XFCE flavour

### ISSUE THREAD

**Issue by antipodes5** [SpiralLinux/SpiralLinux-project#435]
### see also https://github.com/orgs/SpiralLinux/discussions/432

<div type='discussions-op-text'>
Tried installation of XFCE flavour (with bad checksum as discussed, above).
- in live usb form, works great
- installation failed twice - a pop-up declares an error (there is no freeze).

Regrettably, I have no record or log of the failure.

Apologies, I cannot attempt to install again - need this machine for production for the next little while.

**Comment by geckolinux** [comment]
Sorry it didn't work. Whenever you have time to test it again please include a screenshot of the error.
