### ISSUE TITLE
Installed apps won't show on app list

### ISSUE THREAD

**Issue by golf1487** [SpiralLinux/SpiralLinux-project#461]
Installed .deb package with double click.
but after installing the app, it's not available to launch from app list.

**Comment by Ticklezz** [comment]
I noticed this also with .deb of firefox.

**Comment by geckolinux** [comment]
Hi there, we would need a lot more information about this issue in order to properly assess it.
At any rate, the app menu system is configured correctly on all SpiralLinux editions, and any issues in that area would either fall into the realm of the .deb packager or the realm of Debian's development/packaging, which SpiralLinux has no control over.

**Comment by Ticklezz** [comment]
> Hi there, we would need a lot more information about this issue in order to properly assess it. At any rate, the app menu system is configured correctly on all SpiralLinux editions, and any issues in that area would either fall into the realm of the .deb packager or the realm of Debian's development/packaging, which SpiralLinux has no control over.

It just hit me, I wonder if it was the menu editor hiding the apps.

**Comment by Ticklezz** [comment]
![Screenshot from 2024-08-20 19-18-49](https://github.com/user-attachments/assets/a2ed2ade-9030-48d3-a701-038ccbd0931a)
I see this in menu editor. I just installed the .deb file for firefox and it's not there.

**Comment by Ticklezz** [comment]
If I try and execute firefox from the terminal it says command not found. If I install the flatpak of firefox it works and installs just fine.

**Comment by geckolinux** [comment]
A properly designed .deb file for a GUI application should never require manually editing the app menu. At most you might have to logout and login again for the menu system to refresh, but that depends on the desktop environment, which is not specified in this bug report.

The menu editor will definitely create a mess when used improperly as described here. I would suggest that you find all the entries it created by browsing to `~/.local/share/applications/` and sorting the list by recently modified files, and deleting the entries that the menu editor created.

Then, reinstall your Firefox .deb . Logout and login again.

If it still doesn't appear then check what locations the .deb installed its files to by searching for the package you installed in Synaptic and checking the list of installed files under the package's properties. In the case of a Firefox .deb it's probably installed to `/opt/` with a `.desktop` file in `/usr/share/applications/` .
