### ISSUE TITLE
Fails to boot.

### ISSUE THREAD

**Issue by kram1t** [SpiralLinux/SpiralLinux-project#48]
Both the XFCE and MATE iso's fail to boot on a circa 2011 HP box. The following is the output of inxi -M on that machine. I did the checksum steps, it boots fine from straight Debian and LMDE5. So it's a bit of a mystery as to why this machine doesn't like SpiralLinux.
inxi -M
Machine:
  Type: Desktop System: Hewlett-Packard 
  product: HP Compaq dc5800 Small Form Factor v: N/A 
  serial: <superuser required> 
  Mobo: Hewlett-Packard model: 2820h serial: <superuser required> 
  BIOS: Hewlett-Packard v: 786F2 v01.59 date: 07/21/2011 
I can provide more detailed information on the hardware if needed.
-Regards

**Comment by geckolinux** [comment]
Hi there, sorry for the trouble.

Could you please describe what happens when you try to boot it?

I assume that a machine from that era is probably running in legacy BIOS mode (and not EFI)? On EFI systems it's easier to boot the SpiralLinux live ISO with the Debian Stable kernel instead of the much newer Backports kernel that is default. But it is possible in legacy mode to get it to boot the other kernel, if you'd like to try that.

Thanks a lot.

**Comment by geckolinux** [comment]
> But it is possible in legacy mode to get it to boot the other kernel, if you'd like to try that.

![Screenshot from 2022-07-13 09-22-11](https://user-images.githubusercontent.com/2692138/178757154-e4c0a3e3-ce39-412f-8f81-df5f72acdc76.png)

You could also try removing the `quiet loglevel=0 splash` parameters to see where the boot process is failing.

**Comment by kram1t** [comment]
Yes this hardware doesn't use EFI at all. On XFCE I get an error message that says "[FAILED](red text) Failed to start Light Display Manager.". On the MATE one it just gets to a blinking underscore cursor. I'll test the "quiet loglevel=0..." option a test run in a bit. Thanks.

**Comment by kram1t** [comment]
Sorry for the delay, dealing with some getting old health issues. I think you can close this one out. Unfortunately loosejaw (hostname) has decided to retire for good. Maybe the power supply or cpu. It served me well as a test box for about 5 years.

I used the tools included in LinuxMint to format and write the sticks. The graphics chip was a built in Intel  chip. I think that boot option would have been helpful.  Autopsy will be held tomorrow. I'm going to remove the HD to see if I can recovery some of my testing notes.
Many thanks for your help.

**Comment by geckolinux** [comment]
Bummer about the hardware failure. If you do manage to revive it please do give SpiralLinux another try and let us know how it went. Thanks!
