### ISSUE TITLE
Option to install additional fonts

### ISSUE THREAD

**Issue by bungadrum** [SpiralLinux/SpiralLinux-project#489]
Can you add the option to install "fonts-takao" they are not available in Debians software repositories, but they are in Ubuntu would it be possible to add them in Spiral as well since both use the same package manager there shouldn't be compatibility issues. Also is there a option to install "language-pack-ja" in the Language support? I need these 2 packages for a good Debian experience could you add them ?

**Comment by geckolinux** [comment]
Hi there, SpiralLinux does not create its own packages or repositories, it relies entirely on what Debian offers. However, Debian does indeed offer `fonts-takao` , so it's also available in SpiralLinux:
https://packages.debian.org/bookworm/fonts-takao

Debian has different package names for language support compared to Ubuntu, but it supports all the same languages including Japanese. You simply need to set the language of the Calamares installer to Japanese, or else you can change the system language after installation:

![image](https://github.com/user-attachments/assets/2b2352b4-4575-4002-91c8-405a99ba70ed)

![Screenshot from 2024-10-01 08-44-12](https://github.com/user-attachments/assets/4d80606f-e238-4c2b-8f11-49331d4fdb7e)

With that most of the system interfaces will be translated with a few exceptions, mainly LibreOffice, Firefox, and Thunderbird which need their own specific language support packages to be installed like this:

![image](https://github.com/user-attachments/assets/6a6ffc4b-5abd-43d1-9fb5-f9959067052f)

![image](https://github.com/user-attachments/assets/a70608c1-6e74-4e2e-a52f-5d5ae258f542)

You might also find this information useful:
https://github.com/SpiralLinux/SpiralLinux-project/wiki#how-to-install-non-english-input-methods
