### ISSUE TITLE
Request: Brave Browser Installation by Default

### ISSUE THREAD

**Issue by georg41980** [SpiralLinux/SpiralLinux-project#514]
Dear SpiralLinux developer,
I am writing to tell you how enthusiastic I am about SpiralLinux! I have now installed it on my PC for three days and am very satisfied with it.
Unfortunately, the default installation only includes Firefox, which I had problems with, for example, logging into Google. Therefore, I find it better to use a Chromium browser such as Brave, but to equip it with Bitwarden as a password manager.
[Brave-install](https://docs.google.com/document/d/1DLECkMfbV2OKX_a84wnryOMA8gb6MVfUT4HhtRK5BDI/edit?usp=sharing)
Thank you very much for your great work on SpiralLinux!
Sincerely,
Georg Dahmen

**Comment by geckolinux** [comment]
Hi Georg, I'm glad to hear that SpiralLinux is working well for you.
Regarding the browser, that is always a personal choice that the user can easily change, so no changes will be made to the default that comes with SpiralLinux.
