### ISSUE TITLE
SpiralLinux KDE fcitx does not run

### ISSUE THREAD

**Issue by tcitr-chen** [SpiralLinux/SpiralLinux-project#72]
![1](https://user-images.githubusercontent.com/61141667/182751341-076b66d4-0160-46d0-8399-171afb2d475f.png)
![2](https://user-images.githubusercontent.com/61141667/182751439-3d9d5d3e-dc32-45f2-8ed6-2d0de09e87d4.png)
![3](https://user-images.githubusercontent.com/61141667/182751508-56ddbe52-1532-4fb0-b032-43f7dbb0ff87.png)
The keyboard icon in the status bar in the lower right corner is also not showing.

**Comment by geckolinux** [comment]
Hi there, thanks for reporting this.
Would the `fcitx5` framework (version 5) work for your needs? That appears to be what Plasma currently supports:

![Screenshot from 2022-08-04 08-55-51](https://user-images.githubusercontent.com/2692138/182865043-c626093c-6d2d-4b29-8788-c2bd4d5d572f.png)

**Comment by tcitr-chen** [comment]
Thank you, but I want to use fcitx instead of fcitx5, because I am a Chinese user, some input methods can only be installed with fcitx, I tried it on debian 11 kde official live iso, fcitx can run, but not in SpiralLinux, apt repo there is no difference between two isos.

**Comment by geckolinux** [comment]
I see, my apologies that I am not familiar with the the alternate input methods. Please try to install the following highlighted packages in Synaptic:

![Screenshot from 2022-08-04 18-35-05](https://user-images.githubusercontent.com/2692138/182972752-e4648ef0-cf52-4f54-86c0-17ece38affff.png)

**Comment by tcitr-chen** [comment]
Thank you for taking the time to help me find the error.
Unfortunately, I did as you said, and fcitx can indeed be configured in the KDE settings, but the fcitx icon does not appear and the fcitx program itself cannot run.
See the GIF below, all step-by-step.
![1](https://user-images.githubusercontent.com/61141667/182974761-66713fc1-d769-48a6-a1a3-fe7211b1ae6f.gif)
![2](https://user-images.githubusercontent.com/61141667/182974772-b1a8adf3-c578-4fc3-9de9-4fc2d53e8e63.gif)

**Comment by geckolinux** [comment]
Thanks for the reply. Do you have a normal Debian installation available? If so, could you report which `fcitx` packages are installed?

**Comment by tcitr-chen** [comment]
I installed it through the Sourceforge mirror. During the installation process, I selected the English keyboard and language, and only selected China for the time zone.
I installed fcitx using the command sudo apt install fcitx, in the process installed fcitx-frontend-all, then sudo apt install im-config, this problem occurs, but the same operation does not happen in debian 11 KDE kive iso, everything is normal.

**Comment by geckolinux** [comment]
Hello, please login to your Debian installation and report which packages are installed that contain the name `fcitx` .

**Comment by tcitr-chen** [comment]
![图片](https://user-images.githubusercontent.com/61141667/182979283-e2a79f0b-e8b0-4f44-a4ad-6a46bd87173f.png)

**Comment by geckolinux** [comment]
Hi, is this what you are referring to?

![Screenshot from 2022-08-04 20-01-50](https://user-images.githubusercontent.com/2692138/182979910-14b9670a-725c-4d9e-b7cb-2110be95c7dd.png)

To make this work, I installed all the packages that start with `fcitx-` and also `im-config` , and logged out / logged in to Plasma.

**Comment by tcitr-chen** [comment]
yes that's it, make sure it's fcitx4 not fcitx5.
Can you share with me the steps？

**Comment by geckolinux** [comment]
> To make this work, I installed all the packages that start with `fcitx-` and also `im-config` , and logged out / logged in to Plasma.

**Comment by tcitr-chen** [comment]
![图片](https://user-images.githubusercontent.com/61141667/182980652-bcdd6145-ae5c-4095-a128-79a4d93235d9.png)
This is the interface of debian 11 kde fcitx (fcitx4) everything works fine, that picture of yours looks like fcitx5.

**Comment by geckolinux** [comment]
It is fcitx4.

**Comment by geckolinux** [comment]
And if you want the KDE configuration module instead you can install `kde-config-fcitx`:

![Screenshot from 2022-08-04 20-37-51](https://user-images.githubusercontent.com/2692138/182983683-0c4e8c59-e234-4a67-a444-c1b9da4db98b.png)

**Comment by tcitr-chen** [comment]
Yes you are right, need sudo apt install fcitx-*, just sudo apt install fcitx doesn't work, but sudo apt install fcitx works on debian 11 kde live and ubuntu. This is confusing.
