### ISSUE TITLE
Install Fails on System with 32-Bit EFI (Bootloader error)

### ISSUE THREAD

**Issue by Cralex** [SpiralLinux/SpiralLinux-project#90]
Hey there. I have an Acer Aspire Switch 10 (Aspire SW5-015) that I'm trying to install to. The machine is bizarre in that, while the processor supports 64-bit, the EFI is only 32-bit. (There is no legacy boot option, nor is there a firmware update or hack that I'm aware of that makes the EFI support 64-bit.) Because of this needlessly obscure setup, many linux distributions can't even boot install media on it. SpiralLinux can, though, and it even supports the built-in wifi out of the box. Hooray!

...But the install always fails during the bootloader step. The installer complains that running the following command returns an error.

`grub-install --target=i386-efi --efi-directory=/boot/efi --bootloader-id=debian --force` 

Trying this command in the terminal gives me some more details.

`grub-install: error: /usr/lib/grub/i386-efi/modinfo.sh doesn't exist. Please specify --target or --directory`

I've tried this with the xfce, mate, and builder images with the same result.

**Comment by geckolinux** [comment]
Hi there @Cralex , my apologies for not getting back with you on this issue.
I'm currently working on the next set of ISO refreshes for SpiralLinux, and there _might_ be a way to support 32-bit EFI. Would you be available to give a test ISO a spin?

**Comment by geckolinux** [comment]
Support for 32-bit EFI potentially implemented in the SpiralLinux 11.220925 release.
