### ISSUE TITLE
Touchpad not working on mid-2012 MacBook Pro

### ISSUE THREAD

**Issue by RainmakerRaw** [SpiralLinux/SpiralLinux-project#93]
Per title. I have a mid-2012 MacBook Pro which runs great under Debian, *buntu, Fedora, OpenSUSE et al. 

Unfortunately, the latest Spiral live shows no response from the touchpad. It works out of the box on Debian, so I'm guessing this is something that's been removed or overlooked? 

There's no response at all from the touchpad and system settings > touchpad on Plasma version says "No touchpad found". 

I have tried switching out `xserver-xorg-input-multitouch` for `xserver-xorg-input-mtrack`, but still can't get it to work. I'm using the latest image download from your website. Sorry for the poor formatting and brevity, I'm posting from mobile (because my trackpad doesn't work!).

Thanks for any help or pointers.

**Comment by geckolinux** [comment]
Hi there, sorry for the trouble.

Please try uninstalling `xserver-xorg-input-synaptics` and install `xserver-xorg-input-libinput` and `libinput-bin` . Please note that afterwards you will need to kill the current Xorg process with `sudo killall -9 Xorg` or `sudo killall -9 X` (sorry don't remember which it is).

**Comment by RainmakerRaw** [comment]
> Hi there, sorry for the trouble.
> 
> 
> 
> Please try uninstalling `xserver-xorg-input-synaptics` and install `xserver-xorg-input-libinput` and `libinput-bin` . Please note that afterwards you will need to kill the current Xorg process with `sudo killall -9 Xorg` or `sudo killall -9 X` (sorry don't remember which it is).

Thanks so much for the speedy reply! I'll give that a try and report back. I've been using Linux and *BSD for 20 years, and Spiral is such a nice blend of pure Debian and OOTB usability. Or, as I said to someone the other day, "It's what Ubuntu should have been" (sorry-not-sorry). Nice job.

**Comment by geckolinux** [comment]
Really glad you like it! It's encouraging that you say that vanilla Debian works on that MacBook, so that means it's just a matter of finding the missing (or possibly in this case, _excess_) package(s) to make it work.

**Comment by RainmakerRaw** [comment]
> Hi there, sorry for the trouble.
> 
> 
> 
> Please try uninstalling `xserver-xorg-input-synaptics` and install `xserver-xorg-input-libinput` and `libinput-bin` . Please note that afterwards you will need to kill the current Xorg process with `sudo killall -9 Xorg` or `sudo killall -9 X` (sorry don't remember which it is).

It didn't work, unfortunately. According to apt, those packages were already installed (I removed the synaptics one anyway). After killing Xorg and logging back in, still no trackpad recognised. Weird.

**Comment by RainmakerRaw** [comment]
If it's any further help, I didn't have a straight Debian live USB on hand, but last night I booted from the latest stable Devuan (based on Bullseye). The trackpad worked OOTB, and the mouse/trackpad settings show the device as `bcm5974`, whereas on Spiral this is blank.

**Comment by geckolinux** [comment]
Hi there, really sorry for the slow reply.

It looks like the `xserver-xorg-input-mtrack` package is necessary or at least helpful on your hardware. But it looks like the problem is specifically due to a bug in the 5.18 kernel that SpiralLinux uses by default from Backports:
- https://bugzilla.kernel.org/show_bug.cgi?id=215890
- https://bugzilla.kernel.org/show_bug.cgi?id=216140
So, could you please try booting your system with the 5.10 kernel from Debian Stable that is also pre-installed on your system?

**Comment by RainmakerRaw** [comment]
Ah, how typical for a kernel bug to creep in like that, for the first time in years, just as I want to use it haha! 

I don't have Spiral installed atm, for obvious reasons. If the older kernel is available on the live image I'll give it a try. For now, I have Devuan up and running (added bonus of no systemd, which suits my dinosaur experience lol). The machine runs macOS Catalina mostly (i.e. bare metal), but it's getting old and I find booting into Linux tends to do more, faster. 

It's getting to the point where my live USB is running 7-10 days before I 'need' to reboot to macOS and I'm straight back to Linux again. I'm considering wiping it and just sticking with bare metal Linux now, given the machine's age. Hence trying to get Spiral working! Thanks again for your help.

**Comment by geckolinux** [comment]
Ok, thanks for giving it a try. Please report back on the results. Yes, the older kernel version is available on the live ISO as well. If it boots via EFI then you'll have a menu to choose that kernel. If it's in legacy BIOS mode then you'll have to edit the kernel version in the GRUB parameters, please confirm if you need help to change it.

**Comment by RainmakerRaw** [comment]
Yes, the default Debian 5.10 stable kernel fixed it. Thanks again for all the help in getting to the bottom of the issue, I really appreciate you.

**Comment by geckolinux** [comment]
Great, thanks a lot for confirming that. I have no Mac hardware to test, so I appreciate the feedback. Probably the next SpiralLinux release will have a slightly newer kernel from Backports that will avoid the problem. Please let me know if anything else comes up and/or how it goes if you install it.
