### ISSUE TITLE
SpiralLinux Snapshots option in grub turns blank

### ISSUE THREAD

**Issue by emilianomacht** [SpiralLinux/SpiralLinux-project#96]
Hello,

Basically, what the title says. I press that option, grub goes away, and nothing happens no matter what key I press. My only option is to turn off the pc holding the power button. Here's a short video I took:

https://www.youtube.com/watch?v=dZaRmA57yII

Any ideas what's going on?

**Comment by geckolinux** [comment]
Hi there, thanks for reporting this issue.

Well, that's a bit strange. Could you please boot into your system and use the Snapper GUI to generate a new snapshot and try again?

**Comment by emilianomacht** [comment]
I had tried that, but it didn't change anything. In any case, I wanted to do some things on wayland, and I think for my case btrfs is too much of a hassle to manage, so I ended up formatting and installing stock debian. 

Thank you for your help anyway, but you can close or delete this issue.
